### PR TITLE
Code clean-up, added german language

### PR DESCRIPTION
**Pull request by xdevs23**
Clean-up on some files.

Added own StackTraceParser

Added german translation

### CODE REVIEW

**Comment by Thunderbottom** [comment]
Thanks, is the code compiling?

**Comment by xdevs23** [comment]
Did not try, will do that later.

Is something wrong in the code?

If yes, excuse me and let me know.
Am 08.11.2015 06:04 schrieb "Chinmay Pai" notifications@github.com:

**Comment by Thunderbottom** [comment]
No, the Travis CI Build is failing, can you compile once and make sure it is running?

**Comment by xdevs23** [comment]
Oh you mean that? I don't know why it didn't work, it said that travis.yml
is missing.

Sorry, it's the first time I am doing such a pull request.

Would be nice if you can tell me what to do
Am 08.11.2015 15:11 schrieb "Chinmay Pai" notifications@github.com:

**Comment by Thunderbottom** [comment]
Oh yeah, just saw. I'll accept the PR and test it out myself. 

Thanks :)

**Comment by xdevs23** [comment]
No prob.

One thing: I forgot to translate the StirngArrays, can I do this afterwards
and create a new pull request or is it possible to add the file?
Am 08.11.2015 15:41 schrieb "Chinmay Pai" notifications@github.com:

**Comment by Thunderbottom** [comment]
Yes, just make sure you create a PR,
Also, thanks for your StackTraceParser. :+1:

**Comment by xdevs23** [comment]
You're welcome
Am 08.11.2015 16:54 schrieb "Chinmay Pai" notifications@github.com:

**Pull request merged**
