### PR TITLE
Disable youtube background playing

### PR DESCRIPTION
**Pull request by takahirom**
Youtube background playing is useful.
But , Maybe This feature is rejected by Google. If you want to release on Google Play, I recommend that you merge this pull-request.

https://github.com/balzathor/UltimateBrowserProject/issues/45#issuecomment-124945335
https://github.com/mthli/Ninja#why-not-google-play

### CODE REVIEW

**Comment by xdevs23** [comment]
Snap Browser is on Google Play and it is UltimateBrowserProject...

**Comment by xdevs23** [comment]
Do we need this?

Can I close this request or should we keep it open?

**Comment by Thunderbottom** [comment]
No, we'll add this when we put it on PlayStore soon!

**Comment by Thunderbottom** [comment]
so let it be open until then

**Comment by xdevs23** [comment]
Allright.

**Pull request closed without merging**
