### PR TITLE
Minor 1.4.3 Fix (NL)

### PR DESCRIPTION
**Pull request by lucaslampe**
After testing 1.4.3, some minor fixes in translation.

### CODE REVIEW

**Comment by Thunderbottom** [comment]
It won't allow me to merge this, because I already have the exact same translations.
Thanks though :)
I'll check if there's something I need to change and then Change accordingly

Regards.

**Comment by lucaslampe** [comment]
I'm sorry for the misunderstanding. I didn't have the arrays.xml in my local repository and downloaded it manually, which causes GitHub to think I changed it all, but in reality only a couple lines were modified. Take a look.

**Comment by Thunderbottom** [comment]
I've manually updated all of it, don't worry :)

**Comment by Syzew** [comment]
If you want an italian translation, add the folder and i'll work on it

**Comment by Thunderbottom** [comment]
Can you do it by forking? because I'm working on something which is incomplete at this moment and I don't want it to be put up on here.

Regards.

**Comment by Thunderbottom** [comment]
Dutch Translation is already fixed now, so closing. @Syzew if you want to provide Italian strings, fork this project, make a folder called `values-it` and translate `strings.xml` and `arrays.xml` from `values` folder

Regards

**Pull request closed without merging**
