### PR TITLE
Add clicklistener to license listview

### PR DESCRIPTION
**Pull request by takahirom**
Hi!
Open each of the pages when you click in the license dialog item.
screenshot

Regards,

### CODE REVIEW

**Comment by Thunderbottom** [comment]
Thanks a lot, I was gonna do that soon.

Regards.

**Comment by Thunderbottom** [comment]
Now you can push whenever I'm not there, I will be busy for a few days, if you do any updates, you can push it :) Added you to collaborators.

Regards.

**Comment by takahirom** [comment]
Thanks for adding to the collaborator!

**Comment by Thunderbottom** [comment]
Sure :)

**Pull request merged**
