### PR TITLE
Translation Japanese

### PR DESCRIPTION
**Pull request by takahirom**
Hi! This is translation of strings.xml in Japanese(JA).
I want to more contribute to this repository!
Regards,

### CODE REVIEW

**Comment by Thunderbottom** [comment]
Thanks a lot :)
You can help more in development of this application as right now I have other stuff in life to deal with, so updates will kinda be slow at this moment. If you can help in the development in any way, it will be highly appreciated.

**Comment by Thunderbottom** [comment]
Are you on XDA? I'll add you to one of the Contributors there.

**Comment by takahirom** [comment]
Thanks! I registered to XDA!
http://forum.xda-developers.com/member.php?u=6789850

**Comment by Thunderbottom** [comment]
Added you to the contributors there :)

**Pull request merged**
