### PR TITLE
Merge pull request #1 from balzathor/master

### PR DESCRIPTION
**Pull request by davimount**
1.4.4

### CODE REVIEW

**Comment by davimount** [comment]
Opened by mistake, sorry

**Comment by Thunderbottom** [comment]
DUUUUUUUUDE XD

**Comment by davimount** [comment]
Ahahah, my baaaaaad xD

**Comment by Thunderbottom** [comment]
What were you up to anyways? any new contribution?

**Comment by davimount** [comment]
No stable contributions for now. Too busy writing my MSc/MA thesis... I'll be back soon, I hope!

**Comment by Thunderbottom** [comment]
Good luck :+1: :)

**Pull request closed without merging**
