### PR TITLE
[WIP]Add deep link support

### PR DESCRIPTION
**Pull request by takahirom**
It looks like running without problems.
I not sure whether it's behavior are you desired.
Can you test?
#36

### CODE REVIEW

**Comment by Thunderbottom** [comment]
Hey instead of posting a Pull request, you can make a new branch on the main repo. :) There I can test it.

**Comment by takahirom** [comment]
Do you know that you can create pull request on the main repo?
This pull request is created on the main repo.
If you would using github issue, I will close this pull request and use github issue.

**Comment by Thunderbottom** [comment]
No, its fine. You can do whatever you feel is fine :)

If you would `like to use` github issue, I will close this pull request and use github issue :)

**Comment by takahirom** [comment]
Thanks!
This implementation don't ask user whether the user wants to open the Twitter app or go to the webpage.
What do you think about how to ask user?
I suggest to use Snackbar Action.
https://medium.com/ribot-labs/exploring-the-new-android-design-support-library-b7cda56d2c32

**Comment by james9909** [comment]
When prompting the user to open a link with a different app, the browser still loads the url, which should not be the case. This can be fixed by adding <code>return true</code> below <a href="https://github.com/balzathor/UltimateBrowserProject/blob/add-deeplink-support/app/src/main/java/io/github/UltimateBrowserProject/Browser/UltimateBrowserProjectWebViewClient.java#L169">this</a>.

**Comment by takahirom** [comment]
@james9909
Thanks!
I forgot it.
I will add it :)

**Comment by james9909** [comment]
:thumbsup:

**Comment by Thunderbottom** [comment]
Snackbar would be nice, but I suppose the system handles it? Please correct me if I'm wrong.

**Comment by takahirom** [comment]
You are right.
I assumed that you would like to ask user.
#36

```
For example when you click on Twitter link, it should ask user whether the user wants to open the Twitter app or go to the webpage.
```

If deep link , probably open direct the app. It does not ask user.

**Comment by Thunderbottom** [comment]
Oh, so yeah it would be better if we ask the user whether the user wants to open the app. Never do anything without the users consent :D

**Comment by takahirom** [comment]
Sometimes the home and bookmark and history become blank.
It cause when opening new tab.
Because layout width and height become 0...

**Comment by takahirom** [comment]
This layout width and height become 0.
https://github.com/balzathor/UltimateBrowserProject/blob/5611cd89aa90629132aefac9776e1f48d42cd7fe/app/src/main/res/layout/home.xml#L3-3

I think this operation will cause the bug.
https://github.com/balzathor/UltimateBrowserProject/blob/a3e16bd0a2b9893ed9914ca6967e476c509fa188/app/src/main/java/io/github/UltimateBrowserProject/Activity/BrowserActivity.java#L1044-1044

I tried below.
`contentFrame.requestLayout();`

``` java
            contentFrame.removeAllViews();
            contentFrame.addView((View) controller);
            contentFrame.requestLayout();
```

and

`contentFrame.addView((View) controller, CoordinatorLayout.LayoutParams.MATCH_PARENT, CoordinatorLayout.LayoutParams.MATCH_PARENT);`

But, not resolved..

**Comment by Thunderbottom** [comment]
We'll take a look at it :)

**Comment by takahirom** [comment]
Thanks!
I also tried a little more try.

**Comment by Thunderbottom** [comment]
I also tried `a little more`

**Comment by takahirom** [comment]
Thx!

**Comment by takahirom** [comment]
@balzathor 
You can use now. Like this. :)
screen

if you feel that my english text is not good, Please tell me text.

**Comment by Thunderbottom** [comment]
Nice, I'll test it real quick :)
Thanks :D

**Comment by Thunderbottom** [comment]
Can you make the snackbar color to match the omnibox color? that would make it more beautiful

**Comment by takahirom** [comment]
I will do that! :)

**Pull request merged**
