### PR TITLE
Updated English Translations

### PR DESCRIPTION
**Pull request by Recol**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/balzathor/UltimateBrowserProject/pull/62" target="_blank">ReviewNinja

**Comment by Thunderbottom** [comment]
`Looks like you crashed!` doesn't make sense when the application is crashing.

**Comment by xdevs23** [comment]
How about `Looks like the application crashed!`?

**Comment by Recol** [comment]
Updated the fork.

**Comment by Thunderbottom** [comment]
Thanks!

**Comment by xdevs23** [comment]
No prob.

**Pull request merged**
