### PR TITLE
German translation + Language detection

### PR DESCRIPTION
**Pull request by xdevs23**
Here is the new, hopefully working pull request.

Sorry if some files are doubled, I made a mistake when comitting, so I had to commit again.

### CODE REVIEW

**Comment by Thunderbottom** [comment]
Damn, wanted to clean code and you already did it :)
Thanks a ton man! I'm adding you to project contributors so you can create a PR whenever you want to and merge whenever you can.

**Comment by Thunderbottom** [comment]
There you go, now you're a collaborator :)

**Comment by xdevs23** [comment]
No problem, and thank you for adding me :D
Nice to work with you

**Comment by Thunderbottom** [comment]
You can do anything as long as you don't break the application lol

**Comment by xdevs23** [comment]
I don't know how to even break the application, and if it breaks one time,
I could fix it again :D

Oh and I forgot to do something...
In the HTML I made javascript code which automatically inserts the
application version in the title but I forgot the part in the application
code.

You have just to add something like  '"?version=" + appVersion' to the URL
when loading the introduction html.
Am 11.11.2015 20:54 schrieb "Chinmay Pai" notifications@github.com:

**Comment by Thunderbottom** [comment]
So it will be like 
`file:///android_asset/UltimateBrowserProject_introduction_en.html"?version=" + appVersion` 
this?

**Comment by xdevs23** [comment]
Correct.
But appVersion is the String variable containing the version name
String appVersion = getPackageManager()......getVersionName() //would be
2.0, for example
Am 12.11.2015 07:36 schrieb "Chinmay Pai" notifications@github.com:

**Comment by xdevs23** [comment]
"file:///android_asset/UltimateBrowserProject_introduction_en.html?version=" + appVersion

**Comment by Thunderbottom** [comment]
Alright, I'll add it.

**Pull request merged**
