### PR TITLE
Italian localization and icon proposition

### PR DESCRIPTION
**Pull request by davimount**

### CODE REVIEW

**Comment by Thunderbottom** [comment]
Nice Icon, but the color looks a bit dull. Can you make it a bit more bright I'll merge it with the repo :)
YAY for the new icon :D

Regards.

**Comment by davimount** [comment]
Quick color tests, opinions?

ultimatebrowser_logo_0
ultimatebrowser_logo_1
ultimatebrowser_logo_2
ultimatebrowser_logo_3
ultimatebrowser_logo_4
ultimatebrowser_logo_5

**Comment by Thunderbottom** [comment]
First and Last one OP
First looks a bit better

**Comment by davimount** [comment]
Then with shadow and orange tip?

**Comment by Thunderbottom** [comment]
Aye, that would do. Thanks :)

**Comment by davimount** [comment]
Done. We can tweak it more however, in any way, no problems!

**Comment by Thunderbottom** [comment]
Sure
Thanks for your help :) Appreciate it 

Regards.

**Comment by Thunderbottom** [comment]
Can you provide me with a Web-Res Icon so that I can update the banner?

**Comment by davimount** [comment]
512x512
ultimatebrowser_logo_512

1800x1800
ultimatebrowser_logo_1800

2048x2048
ultimatebrowser_logo_2048

**Comment by Thunderbottom** [comment]
Thanks a lot mate :)

**Pull request merged**
