### PR TITLE
Add action to save link

### PR DESCRIPTION
**Pull request by james9909**
Added an action to save a link, which could be merged with the save picture action, but I wasn't sure if you wanted that.

### CODE REVIEW

**Comment by Thunderbottom** [comment]
Thanks, never knew `guessContentTypeFromName` was a thing. Like I supposed there should be but never knew.

**Comment by Thunderbottom** [comment]
This would work but I'd love to save the link when it is open, is there a way to do that too?

**Comment by james9909** [comment]
What files would it automatically save on? Just txt files?

**Comment by Thunderbottom** [comment]
Any file format, like jpeg, text.

**Comment by takahirom** [comment]
Sorry for my bad English.
If you know how to distinguish download contents, probably you can implement in shouldOverrideUrlLoading() .
https://github.com/balzathor/UltimateBrowserProject/blob/ada47ff26413effe57f759c8bd96d3be31f478e6/app/src/main/java/io/github/UltimateBrowserProject/Browser/UltimateBrowserProjectWebViewClient.java#L91

**Comment by Thunderbottom** [comment]
But user always doesn't want to download the file, so opening will occur online and if he wants to save the file, he can do so through one click.

**Comment by james9909** [comment]
Where would this one click be?

**Comment by Thunderbottom** [comment]
Below this line https://github.com/balzathor/UltimateBrowserProject/blob/master/app/src/main/java/io/github/UltimateBrowserProject/Activity/BrowserActivity.java#L1616

**Comment by Thunderbottom** [comment]
And how it should do it would go here https://github.com/balzathor/UltimateBrowserProject/blob/master/app/src/main/java/io/github/UltimateBrowserProject/Activity/BrowserActivity.java#L1689

**Comment by Thunderbottom** [comment]
Sorry if this has an easy solution, but I'm still learning so I'm pretty confused on how to do it.

**Comment by Thunderbottom** [comment]
Nevermind, fixed it on my own, will upload after some immense testing.
Thanks for the help :)

**Comment by Thunderbottom** [comment]
Adding this, plus adding the other one too. More features! Thanks :)
Appreciate the help

**Comment by james9909** [comment]
No problem :)

**Comment by takahirom** [comment]
:+1:

**Pull request merged**
