### PR TITLE
Completed German translation + added german HTML

### PR DESCRIPTION
**Pull request by xdevs23**

### CODE REVIEW

**Comment by Thunderbottom** [comment]
You need to add the HTML file [here below this line](https://github.com/balzathor/UltimateBrowserProject/blob/7e2b7b7c971e6fa3ad4cd6c382f5b3f5dfefb035/app/src/main/java/io/github/UltimateBrowserProject/Unit/BrowserUnit.java#L65) and then edit the system language detection [here somewhere](https://github.com/balzathor/UltimateBrowserProject/blob/7e2b7b7c971e6fa3ad4cd6c382f5b3f5dfefb035/app/src/main/java/io/github/UltimateBrowserProject/Activity/BrowserActivity.java#L291)

**Comment by xdevs23** [comment]
@balzathor I have done that now, check it out :D

**Comment by xdevs23** [comment]
Sorry, forgot to import java.util.Locale

**Comment by Thunderbottom** [comment]
This branch has issues, let me see

**Comment by xdevs23** [comment]
How can I pull your commits into my branch  while a pull request is active?

I am a few commits behind you but dont find a way to pull them because this pull request is currently active.

**Comment by Thunderbottom** [comment]
You'll need to fork again

**Comment by xdevs23** [comment]
Don't I have 2 branches then?

**Comment by Thunderbottom** [comment]
No you can just fork it again and write 2 lines of code, or are you fine with me manually including it?

**Comment by xdevs23** [comment]
So, I need to delete the branch, fork it, and change the two files
BrowserActivity.java and BrowserUnit.java?

That would be no problem
Am 10.11.2015 19:07 schrieb "Chinmay Pai" notifications@github.com:

**Comment by xdevs23** [comment]
Sorry that I ask so much, I don't have that much experience with github and I am very new to it, so please understand me and have patience, thank you very much.

**Comment by Thunderbottom** [comment]
Its fine, everyone has to start somewhere :)

**Comment by xdevs23** [comment]
Oh thank you :D
Am 11.11.2015 06:15 schrieb "Chinmay Pai" notifications@github.com:

**Pull request closed without merging**
