### PR TITLE
Add fullscreen mode

### PR DESCRIPTION
**Pull request by james9909**
Upon enabling fullscreen mode, the status bar and omnibox hides itself when in a web page. The omnibox can made visible again by scrolling up, and hides itself when you scroll down.
However when the omnibox hides itself, a gray line is left behind, and I'm not entirely sure as to where it came from. If you know the id of the line, that would be great.

### CODE REVIEW

**Comment by Thunderbottom** [comment]
I suppose the gray line that you're seeing is the scroll bar, can you try disabling the scroll bar in settings and then see if that gray line still exists? If it does then we can disable scroll bar when Fullscreen mode is active

**Comment by Thunderbottom** [comment]
Have you tested this yet?^

**Comment by james9909** [comment]
The scroll bar in the settings is disabled yet the problem persists. Also I'm adding support for when the omnibox is anchored at the bottom.

**Comment by Thunderbottom** [comment]
Can you post a screenshot of how it looks like? that gray bar is unknown, maybe a visual bug.

**Comment by james9909** [comment]
The one at the top

**Comment by Thunderbottom** [comment]
Can you upload a debug apk? I'll test it on some devices and check where the problem is, I'm not sure of what that is.

**Comment by james9909** [comment]
Ugh I'm not home at the moment and iI won't be for several hours.

**Comment by Thunderbottom** [comment]
Alright, take your time.

**Comment by Thunderbottom** [comment]
Oh wait, I suppose that is the progress bar, which shows the Page Load progress. You can check that [here](https://github.com/balzathor/UltimateBrowserProject/blob/master/app/src/main/java/io/github/UltimateBrowserProject/Activity/BrowserActivity.java#L1260)

**Comment by Thunderbottom** [comment]
And a few lines above that, basically you'll have to set the visibility of the progress bar as `progressBar.setVisibility(View.GONE);`

**Comment by james9909** [comment]
I think I tried that already

**Comment by Thunderbottom** [comment]
I'm pretty much sure that its the `progressBar`

**Comment by james9909** [comment]
Well I've managed to get the apk off my phone https://drive.google.com/folder/d/0B3jK3ytaEqnDX0VlMjBYT0ZzMTg/edit
Oh and the apk has the bottom omnibox full screen thing which is wip

**Comment by Thunderbottom** [comment]
Alright I'll give it a look, thanks :)

**Comment by Thunderbottom** [comment]
Also, can you hide the omnibar while scrolling the page on non fullscreen mode? That would be sweet!

**Comment by james9909** [comment]
Yeah sure

**Comment by Thunderbottom** [comment]
Nice, also, is there a sort of animation that Chrome uses to hide the bar while scrolling or does it happen without that, cause when I'm scrolling in fullscreen mode, the omnibar is glitching out instead of smoothly going our of visibility. This isn't a problem, just a question cause I'm sort of curious to know how that takes place.

**Comment by james9909** [comment]
Yeah the animations need to be tweaked

**Comment by Thunderbottom** [comment]
Oh, I've always wondered on how they do that.

**Comment by james9909** [comment]
Also if you tried the fullscreen when the omnibox is anchored at the bottom then you've noticed that the web view shifts down. Do you know how to fix this?

**Comment by Thunderbottom** [comment]
You'll have to do the same thing like you did with top, but this time with bottom, look here, there are two files separate for [Top](https://github.com/balzathor/UltimateBrowserProject/blob/master/app/src/main/res/layout/main_top.xml) and [Bottom](https://github.com/balzathor/UltimateBrowserProject/blob/master/app/src/main/res/layout/main_bottom.xml) which function independently when set in the settings.

**Comment by Thunderbottom** [comment]
Basically what you're doing is hiding the omnibox from the default position, i.e. top, but due to similar functioning, you can hide bottom omnibox too. But due to this, a space is created at the top part.

**Comment by Thunderbottom** [comment]
So you'll have to make 2 different sets of methods for it to work i suppose.

**Comment by james9909** [comment]
Can't I just use separate animations?

**Comment by james9909** [comment]
woops

**Comment by Thunderbottom** [comment]
You can use separate animations though I'm not sure about it. Give it a try.

**Comment by Thunderbottom** [comment]
Also, now you're included in one of the Project Collaborators, If you are sure about your feature, you can make a new branch on the main project, and add the feature there, after testing that feature will be added to the main branch :) Thanks for your support :D 

Regards.

**Comment by james9909** [comment]
Will make new branch

**Comment by Thunderbottom** [comment]
Remove the bottom scrolling hiding the omnibox feature, It looks better when it doesn't hide. Let it be there for top, but for bottom, the original feature would do good.

**Pull request closed without merging**
