### PR TITLE
Updated English translations

### PR DESCRIPTION
**Pull request by Recol**
Fixed grammar, spelling and sentence structure.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/balzathor/UltimateBrowserProject/pull/61" target="_blank">ReviewNinja

**Comment by Thunderbottom** [comment]
Hey man, could you add a '\' before every apostrophe in the list? It's very much needed there.

**Comment by Recol** [comment]
Whoops, sorry, will do.

**Comment by Thunderbottom** [comment]
Just update your fork with the '\' and it will be automatically pulled here!

**Comment by Recol** [comment]
Updated the fork.

**Pull request merged**
